/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect, react-hooks/exhaustive-deps, @next/next/no-img-element */
"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, CalendarCheck, ChevronLeft, Download, HeartHandshake, Menu, Plus, RefreshCw, Save, Trash2, Users, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { loadData, mutateData, type AppData } from "@/lib/data";
import { canManageDaara, canManageKourel, canManageMembers, canManageSocial, roleLabels, type UserRole } from "@/lib/roles";

declare global {
  interface Document {
    modelContext?: { registerTool: (tool: any, options?: { signal?: AbortSignal }) => void | Promise<void> };
  }
}

type View = "dashboard" | "members" | "activities" | "social" | "reports";
type Data = AppData;
const emptyData: Data = { members: [], renewals: [], activities: [], attendance: [], contributions: [], socialEvents: [], cashMovements: [] };
const today = new Date().toISOString().slice(0, 10);
const currentMonth = today.slice(0, 7);
const currentYear = Number(today.slice(0, 4));
const kourels = ["Nourou Dareyni", "Mafatikhoul Bisri", "Adolescent"];
const spaces = ["ECH", "ECF", "ECE"];
const statusLabels: Record<string, string> = { present: "Présent", late: "Présent en retard", absent: "Absent", justified: "Absent justifié" };

export default function SharedApp({ user, onSignOut }: { user: { id: string; name: string; identifier: string; role: UserRole }; onSignOut: () => void }) {
  const [view, setView] = useState<View>("dashboard");
  const [menuOpen, setMenuOpen] = useState(false);
  const [data, setData] = useState<Data>(emptyData);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  async function load() { setLoading(true); try { setData(await loadData()); } catch (error) { setMessage(error instanceof Error ? error.message : "Erreur de chargement"); } finally { setLoading(false); } }
  async function mutate(payload: any, success: string) { setBusy(true); setMessage(""); try { await mutateData(payload, user.id); setMessage(success); await load(); return true; } catch (error) { setMessage(error instanceof Error ? error.message : "Erreur d'enregistrement"); return false; } finally { setBusy(false); } }
  useEffect(() => { void load(); }, [user.id]);
  useEffect(() => {
    const context = typeof document === "undefined" ? undefined : document.modelContext;
    if (!user || !context?.registerTool) return;
    const lifecycle = new AbortController();
    const register = (tool: any) => { try { void Promise.resolve(context.registerTool(tool, { signal: lifecycle.signal })).catch(() => undefined); } catch { /* Unsupported WebMCP host. */ } };
    register({ name: "list_members", title: "Lister les membres", description: "Retourne la liste actuelle des membres avec leur matricule, kourel et espace culturel.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: false }, execute: async () => ({ count: data.members.length, members: data.members.map(({ id, matricule, prenom, nom, kourel, culturalSpace }) => ({ id, matricule, prenom, nom, kourel, culturalSpace })) }) });
    if (canManageSocial(user.role)) register({ name: "record_monthly_contribution", title: "Enregistrer une cotisation", description: "Enregistre ou annule la cotisation sociale mensuelle de 1 000 FCFA pour un membre.", inputSchema: { type: "object", properties: { memberId: { type: "string" }, month: { type: "string", pattern: "^[0-9]{4}-[0-9]{2}$" }, paid: { type: "boolean" } }, required: ["memberId", "month", "paid"], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: async (input: any) => { if (!data.members.some(m => m.id === input.memberId)) throw new Error("Membre introuvable"); const ok = await mutate({ action: "toggleContribution", memberId: input.memberId, month: input.month, paid: input.paid }, input.paid ? "Cotisation enregistrée" : "Cotisation annulée"); if (!ok) throw new Error("Échec de l'enregistrement"); return { ok: true, memberId: input.memberId, month: input.month, amount: input.paid ? 1000 : 0 }; } });
    return () => lifecycle.abort();
  }, [user, data]);
  const title = { dashboard: "Tableau de bord", members: "Membres", activities: "Activités et présences", social: "Gestion sociale", reports: "Statistiques" }[view];
  const nav = [
    { key: "dashboard" as View, Icon: Activity, label: "Tableau de bord", show: true },
    { key: "members" as View, Icon: Users, label: "Membres", show: canManageMembers(user.role) },
    { key: "activities" as View, Icon: CalendarCheck, label: "Activités", show: canManageDaara(user.role) || canManageKourel(user.role) },
    { key: "social" as View, Icon: HeartHandshake, label: "Social", show: canManageSocial(user.role) },
    { key: "reports" as View, Icon: BarChart3, label: "Statistiques", show: user.role !== "social" },
  ].filter(item => item.show);
  return <div className="app-shell"><aside className={`app-sidebar ${menuOpen ? "open" : ""}`}><div className="brand-lockup"><img src="/logo-ht.jpg" alt="Logo Hizbut-Tarqiyyah" /><div><strong>HT Gestion</strong><small>des membres</small></div></div><nav>{nav.map(({ key, Icon, label }) => <button key={key} className={view === key ? "active" : ""} onClick={() => { setView(key); setMenuOpen(false); }}><Icon />{label}</button>)}</nav><div className="account-card"><strong>{user.name}</strong><span>{roleLabels[user.role]} · {user.identifier}</span><button type="button" onClick={onSignOut}>Se déconnecter</button></div></aside>{menuOpen && <button className="menu-backdrop" aria-label="Fermer le menu" onClick={() => setMenuOpen(false)} />}<main className="app-main"><header className="app-header"><Button variant="outline" size="icon" className="mobile-menu" onClick={() => setMenuOpen(true)}><Menu /></Button><div><p>HT Gestion des membres</p><h1>{title}</h1></div><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? "animate-spin" : ""} /><span className="desktop-only">Actualiser</span></Button></header>{message && <div className="app-message">{message}</div>}<div className="app-content">{loading ? <Loading /> : view === "dashboard" ? <Dashboard data={data} setView={setView} role={user.role} /> : view === "members" && canManageMembers(user.role) ? <MembersView data={data} mutate={mutate} busy={busy} /> : view === "activities" && (canManageDaara(user.role) || canManageKourel(user.role)) ? <ActivitiesView data={data} mutate={mutate} busy={busy} role={user.role} /> : view === "social" && canManageSocial(user.role) ? <SocialView data={data} mutate={mutate} busy={busy} /> : view === "reports" && user.role !== "social" ? <ReportsView data={data} /> : <Dashboard data={data} setView={setView} role={user.role} />}</div></main></div>;
}
function Loading() { return <div className="loading-card"><RefreshCw className="animate-spin" /><p>Chargement des données partagées...</p></div>; }
function Panel({ title, action, children }: any) { return <section className="panel"><header><h2>{title}</h2>{action}</header><div className="panel-body">{children}</div></section>; }
function Metric({ label, value, detail, danger }: any) { return <article className={`metric ${danger ? "danger" : ""}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
function Quick({ icon: Icon, title, text, onClick }: any) { return <button className="quick-card" onClick={onClick}><span><Icon /></span><strong>{title}</strong><small>{text}</small></button>; }
function Empty({ text }: { text: string }) { return <div className="empty-state">{text}</div>; }
function ageFrom(date: string) { if (!date) return "-"; const birth = new Date(date); const now = new Date(); let age = now.getFullYear() - birth.getFullYear(); if (now < new Date(now.getFullYear(), birth.getMonth(), birth.getDate())) age--; return age; }
function memberName(member: any) { return member ? `${member.prenom} ${member.nom}` : "Membre supprimé"; }
function Field({ label, wide, value, ...props }: any) { return <label className={wide ? "field wide" : "field"}><span>{label}</span><Input defaultValue={value || ""} {...props} /></label>; }
function SelectField({ label, options, value, wide, optionObjects, ...props }: any) { return <label className={wide ? "field wide" : "field"}><span>{label}</span><NativeSelect defaultValue={value || ""} {...props}><NativeSelectOption value="">Sélectionner</NativeSelectOption>{options.map((option: any) => <NativeSelectOption key={optionObjects ? option.value : option} value={optionObjects ? option.value : option}>{optionObjects ? option.label : option}</NativeSelectOption>)}</NativeSelect></label>; }

function Dashboard({ data, setView, role }: { data: Data; setView: (view: View) => void; role: UserRole }) {
  const renewed = new Set(data.renewals.filter(r => r.year === currentYear).map(r => r.memberId)); const income = data.contributions.reduce((s, x) => s + x.amount, 0) + data.cashMovements.filter(x => x.type === "income").reduce((s, x) => s + x.amount, 0); const expenses = data.cashMovements.filter(x => x.type === "expense").reduce((s, x) => s + x.amount, 0);
  return <><section className="metric-grid"><Metric label="Membres" value={data.members.length} detail={`${renewed.size} renouvelé(s) en ${currentYear}`} />{role !== "social" && <Metric label="Activités du mois" value={data.activities.filter(a => a.date?.startsWith(currentMonth)).length} detail={currentMonth} />}{canManageSocial(role) && <Metric label="Cotisations du mois" value={data.contributions.filter(x => x.month === currentMonth).length} detail={`${data.members.length} attendu(s)`} />}{canManageSocial(role) && <Metric label="Solde social" value={`${(income - expenses).toLocaleString("fr-FR")} F`} detail={`${income.toLocaleString("fr-FR")} F d'entrées`} danger={income - expenses < 0} />}</section><section className="quick-grid">{canManageMembers(role) && <Quick icon={Users} title="Gérer les membres" text="Inscriptions et renouvellements annuels" onClick={() => setView("members")} />}{(canManageDaara(role) || canManageKourel(role)) && <Quick icon={CalendarCheck} title="Gérer les activités" text={canManageDaara(role) && canManageKourel(role) ? "Daara, répétitions et prestations" : canManageDaara(role) ? "Activités de la Daara" : "Répétitions et prestations"} onClick={() => setView("activities")} />}{canManageSocial(role) && <Quick icon={Wallet} title="Gérer la caisse" text="Cotisations, évènements et mouvements" onClick={() => setView("social")} />}</section>{role !== "social" && <Panel title="Activités récentes"><ActivityList data={data} limit={6} /></Panel>}</>;
}

function MembersView({ data, mutate, busy }: any) {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<any>(null); const [query, setQuery] = useState(""); const renewed = new Set(data.renewals.filter((r: any) => r.year === currentYear).map((r: any) => r.memberId)); const visible = data.members.filter((m: any) => `${m.matricule} ${m.prenom} ${m.nom} ${m.kourel}`.toLowerCase().includes(query.toLowerCase()));
  function start(member?: any) { setEditing(member || { registrationDate: today }); setOpen(true); }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const member: any = Object.fromEntries(form.entries()); member.id = editing?.id; if (await mutate({ action: "saveMember", member, renewal: { year: Number(form.get("renewalYear")), date: form.get("renewalDate") } }, editing?.id ? "Informations actualisées" : "Membre inscrit")) setOpen(false); }
  return <Panel title="Liste des membres" action={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button onClick={() => start()}><Plus />Ajouter</Button></DialogTrigger><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{editing?.id ? "Actualiser le membre" : "Inscrire un membre"}</DialogTitle></DialogHeader><form className="form-grid" onSubmit={submit}><Field name="matricule" label="Matricule" value={editing?.matricule} required readOnly={Boolean(editing?.id)} /><Field name="prenom" label="Prénom" value={editing?.prenom} required /><Field name="nom" label="Nom" value={editing?.nom} required /><SelectField name="sexe" label="Sexe" value={editing?.sexe} options={["Femme", "Homme"]} /><Field name="birthDate" label="Date de naissance" type="date" value={editing?.birthDate} /><Field name="phone" label="Téléphone" value={editing?.phone} /><Field name="email" label="E-mail" type="email" value={editing?.email} /><Field name="address" label="Adresse" value={editing?.address} wide /><Field name="profession" label="Profession" value={editing?.profession} /><Field name="daaraSector" label="Secteur dans la Daara" value={editing?.daaraSector} /><Field name="magalSector" label="Secteur au Grand Magal" value={editing?.magalSector} /><SelectField name="culturalSpace" label="Espace culturel" value={editing?.culturalSpace} options={spaces} /><SelectField name="kourel" label="Kourel" value={editing?.kourel} options={kourels} /><Field name="registrationDate" label="Première inscription" type="date" value={editing?.registrationDate || today} /><Field name="renewalYear" label="Année de renouvellement" type="number" value={currentYear} /><Field name="renewalDate" label="Date du renouvellement" type="date" value={today} /><Button className="wide" type="submit" disabled={busy}><Save />Enregistrer</Button></form></DialogContent></Dialog>}><div className="toolbar"><Input placeholder="Rechercher par matricule, nom ou kourel" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="list-lines">{visible.length ? visible.map((m: any) => <article className="member-line" key={m.id}><div className="member-avatar">{m.prenom?.[0]}{m.nom?.[0]}</div><div className="member-main"><strong>{m.prenom} {m.nom}</strong><span>{m.matricule} · {m.kourel || "Sans kourel"} · {m.culturalSpace || "Sans espace"}</span></div><div className="member-meta"><span>{ageFrom(m.birthDate)} ans</span><b className={renewed.has(m.id) ? "status-ok" : "status-warn"}>{renewed.has(m.id) ? `Renouvelé ${currentYear}` : "À renouveler"}</b></div><div className="row-actions"><Button variant="outline" size="sm" onClick={() => start(m)}>Modifier</Button><Button variant="ghost" size="icon" aria-label="Supprimer" onClick={() => confirm("Supprimer ce membre ?") && void mutate({ action: "delete", entity: "member", id: m.id }, "Membre supprimé")}><Trash2 /></Button></div></article>) : <Empty text="Aucun membre trouvé." />}</div></Panel>;
}

function ActivitiesView({ data, mutate, busy, role }: any) {
  const allowKourel = canManageKourel(role); const allowDaara = canManageDaara(role); const [section, setSection] = useState<"kourel" | "daara">(allowKourel ? "kourel" : "daara"); const [open, setOpen] = useState(false); const [kourel, setKourel] = useState(kourels[0]); const [type, setType] = useState("Répétition"); const [statuses, setStatuses] = useState<Record<string, string>>({}); const [filterDate, setFilterDate] = useState(today); const roster = section === "kourel" ? data.members.filter((m: any) => m.kourel === kourel) : data.members; const allowed = section === "kourel" ? ["present", "late", "absent", "justified"] : ["present", "absent"];
  function begin() { setStatuses(Object.fromEntries(roster.map((m: any) => [m.id, "present"]))); setOpen(true); }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const activity: any = Object.fromEntries(form.entries()); activity.scope = section === "kourel" ? "kourel" : "general"; activity.kourel = section === "kourel" ? kourel : "Tous"; activity.type = section === "kourel" ? type : activity.type; activity.melodies = String(form.get("melodies") || "").split("\n").map(x => x.trim()).filter(Boolean); if (await mutate({ action: "saveActivity", activity, attendance: statuses }, "Fiche de présence enregistrée")) setOpen(false); }
  return <>{allowKourel && allowDaara && <div className="section-tabs"><Button variant={section === "kourel" ? "default" : "outline"} onClick={() => setSection("kourel")}>Répétition / Prestation</Button><Button variant={section === "daara" ? "default" : "outline"} onClick={() => setSection("daara")}>Activités de la Daara</Button></div>}<Panel title={section === "kourel" ? "Répétitions et prestations" : "Activités de la Daara"} action={<Button onClick={begin}><Plus />Nouvelle activité</Button>}><div className="toolbar">{section === "kourel" && <NativeSelect value={kourel} onChange={e => setKourel(e.target.value)}>{kourels.map(x => <NativeSelectOption key={x}>{x}</NativeSelectOption>)}</NativeSelect>}<label className="inline-field"><span>Date</span><Input type="date" value={filterDate} onChange={e => setFilterDate(e.target.value)} /></label></div><ActivityList data={data} date={filterDate} scope={section === "kourel" ? "kourel" : "general"} kourel={section === "kourel" ? kourel : undefined} /></Panel><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[94vh] overflow-y-auto sm:max-w-5xl"><DialogHeader><DialogTitle>Nouvelle fiche de présence</DialogTitle></DialogHeader><form onSubmit={submit}><div className="form-grid">{section === "kourel" ? <><SelectField name="typeDisplay" label="Activité" value={type} options={["Répétition", "Prestation"]} onChange={(e: any) => setType(e.target.value)} /><SelectField name="kourelDisplay" label="Kourel" value={kourel} options={kourels} onChange={(e: any) => setKourel(e.target.value)} /></> : <><SelectField name="type" label="Activité de la Daara" value="Animation" options={["Animation", "AG locale", "AG Direction générale"]} /><SelectField name="culturalSpace" label="Espace culturel" options={spaces} /></>}<Field name="date" label="Jour" type="date" value={today} required /><Field name="place" label="Lieu" required /><Field name="startTime" label="Heure de début" type="time" /><Field name="endTime" label="Heure de fin" type="time" />{section === "kourel" && type === "Prestation" && <Field name="eventName" label="Nom de l'évènement" required wide />}{section === "kourel" && <label className="field wide"><span>Mélodies, une par ligne</span><Textarea name="melodies" placeholder="Mélodie 1&#10;Mélodie 2" /></label>}</div><h3 className="subheading">Pointage des membres ({roster.length})</h3><AttendanceEditor members={roster} allowed={allowed} statuses={statuses} setStatuses={setStatuses} /><div className="sticky-save"><Button type="submit" disabled={busy || !roster.length}><Save />Enregistrer la présence</Button></div></form></DialogContent></Dialog></>;
}

function AttendanceEditor({ members, allowed, statuses, setStatuses }: any) { return <div className="attendance-list">{members.length ? members.map((m: any) => <article key={m.id}><div><strong>{m.prenom} {m.nom}</strong><span>{m.matricule}</span></div><div className="status-options">{allowed.map((status: string) => <label key={status} className={statuses[m.id] === status ? `selected ${status}` : ""}><input type="radio" name={`status-${m.id}`} checked={statuses[m.id] === status} onChange={() => setStatuses((old: any) => ({ ...old, [m.id]: status }))} />{statusLabels[status]}</label>)}</div></article>) : <Empty text="Aucun membre dans cette sélection." />}</div>; }
function ActivityList({ data, limit, date, scope, kourel }: any) { let rows = data.activities.filter((a: any) => (!date || a.date === date) && (!scope || a.scope === scope) && (!kourel || a.kourel === kourel)); if (limit) rows = rows.slice(0, limit); return <div className="activity-list">{rows.length ? rows.map((a: any) => { const records = data.attendance.filter((x: any) => x.activityId === a.id); return <article key={a.id}><time>{a.date}</time><div><strong>{a.type}{a.eventName ? ` · ${a.eventName}` : ""}</strong><span>{a.kourel !== "Tous" ? `${a.kourel} · ` : ""}{a.place || "Lieu non renseigné"} · {a.startTime || "--:--"}</span><div className="count-chips">{Object.keys(statusLabels).map(s => { const count = records.filter((x: any) => x.status === s).length; return count ? <b key={s} className={s}>{statusLabels[s]} : {count}</b> : null; })}</div></div></article>; }) : <Empty text={date ? "Aucune activité à cette date." : "Aucune activité enregistrée."} />}</div>; }

function SocialView({ data, mutate, busy }: any) {
  const [page, setPage] = useState<"home" | "contributions" | "event" | "cash">("home"); const [month, setMonth] = useState(currentMonth); const income = data.contributions.reduce((s: number, x: any) => s + x.amount, 0) + data.cashMovements.filter((x: any) => x.type === "income").reduce((s: number, x: any) => s + x.amount, 0); const expenses = data.cashMovements.filter((x: any) => x.type === "expense").reduce((s: number, x: any) => s + x.amount, 0); const balance = income - expenses;
  async function submitEvent(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); if (await mutate({ action: "addSocialEvent", event: { ...Object.fromEntries(f.entries()), kourelPerformance: f.has("kourelPerformance") } }, "Évènement social enregistré")) setPage("home"); }
  async function submitCash(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); if (await mutate({ action: "addCashMovement", movement: Object.fromEntries(f.entries()) }, "Mouvement de caisse enregistré")) setPage("home"); }
  if (page === "contributions") return <><Back onClick={() => setPage("home")} label="Cotisations mensuelles" /><Panel title="Suivi des cotisations de 1 000 FCFA" action={<Input type="month" value={month} onChange={e => setMonth(e.target.value)} />}><div className="contribution-list">{data.members.map((m: any) => { const paid = data.contributions.some((x: any) => x.memberId === m.id && x.month === month); return <label key={m.id}><Checkbox checked={paid} disabled={busy} onCheckedChange={(checked) => void mutate({ action: "toggleContribution", memberId: m.id, month, paid: checked === true }, checked ? "Cotisation enregistrée" : "Cotisation annulée")} /><div><strong>{memberName(m)}</strong><span>{m.matricule} · {m.kourel || "Sans kourel"}</span></div><b className={paid ? "status-ok" : "status-warn"}>{paid ? "Payé" : "Non payé"}</b></label>; })}</div></Panel></>;
  if (page === "event") return <><Back onClick={() => setPage("home")} label="Nouvel évènement social" /><Panel title="Renseigner l'évènement"><form className="form-grid" onSubmit={submitEvent}><SelectField name="memberId" label="Membre concerné" options={data.members.map((m: any) => ({ value: m.id, label: memberName(m) }))} optionObjects required /><SelectField name="type" label="Nature" options={["Baptême", "Mariage", "Décès", "Décès d'un proche"]} required /><Field name="date" label="Date" type="date" value={today} required /><Field name="expenseAmount" label="Montant effectivement remis" type="number" min="0" value="0" /><label className="check-field wide"><Checkbox name="kourelPerformance" /> Une prestation du kourel a eu lieu</label><label className="field wide"><span>Observations</span><Textarea name="note" /></label><Button type="submit" className="wide" disabled={busy}><Save />Enregistrer</Button></form></Panel></>;
  if (page === "cash") return <><Back onClick={() => setPage("home")} label="Mouvement de caisse" /><Panel title="Nouvelle entrée ou sortie"><form className="form-grid" onSubmit={submitCash}><SelectField name="type" label="Type" options={[{ value: "income", label: "Entrée" }, { value: "expense", label: "Sortie" }]} optionObjects required /><Field name="date" label="Date" type="date" value={today} required /><Field name="label" label="Libellé" required wide /><Field name="amount" label="Montant (FCFA)" type="number" min="1" required /><Button type="submit" className="wide" disabled={busy}><Save />Enregistrer</Button></form></Panel><Panel title="Derniers mouvements"><CashList data={data} /></Panel></>;
  return <><section className="metric-grid social-metrics"><Metric label="Entrées" value={`${income.toLocaleString("fr-FR")} F`} detail="Cotisations et autres entrées" /><Metric label="Sorties" value={`${expenses.toLocaleString("fr-FR")} F`} detail="Aides et dépenses" /><Metric label="Montant disponible" value={`${balance.toLocaleString("fr-FR")} F`} detail={balance < 0 ? "Déficit de caisse" : "Caisse disponible"} danger={balance < 0} /></section>{balance < 0 && <div className="deficit-alert">Alerte : déficit de {Math.abs(balance).toLocaleString("fr-FR")} FCFA.</div>}<section className="social-actions"><button onClick={() => setPage("contributions")}><Wallet /><strong>Cotisations mensuelles</strong><span>Suivre les versements de 1 000 FCFA</span></button><button onClick={() => setPage("event")}><HeartHandshake /><strong>Nouvel évènement social</strong><span>Baptême, mariage ou décès</span></button><button onClick={() => setPage("cash")}><Activity /><strong>Mouvement de caisse</strong><span>Enregistrer une entrée ou une sortie</span></button></section><Panel title="Évènements récents"><div className="event-list">{data.socialEvents.length ? data.socialEvents.slice(0, 8).map((e: any) => <article key={e.id}><time>{e.date}</time><div><strong>{e.type} · {memberName(data.members.find((m: any) => m.id === e.memberId))}</strong><span>{e.expenseAmount.toLocaleString("fr-FR")} FCFA remis{e.kourelPerformance ? " · Prestation du kourel" : ""}</span></div></article>) : <Empty text="Aucun évènement social." />}</div></Panel></>;
}
function Back({ onClick, label }: any) { return <div className="back-title"><Button variant="ghost" onClick={onClick}><ChevronLeft />Retour</Button><h2>{label}</h2></div>; }
function CashList({ data }: { data: Data }) { return <div className="event-list">{data.cashMovements.length ? data.cashMovements.slice(0, 10).map((x: any) => <article key={x.id}><time>{x.date}</time><div><strong>{x.label}</strong><span>{x.type === "income" ? "Entrée" : "Sortie"}</span></div><b className={x.type}>{x.type === "income" ? "+" : "-"}{x.amount.toLocaleString("fr-FR")} F</b></article>) : <Empty text="Aucun mouvement de caisse." />}</div>; }

function ReportsView({ data }: { data: Data }) {
  const [period, setPeriod] = useState<"month" | "year">("month"); const [month, setMonth] = useState(currentMonth); const [year, setYear] = useState(String(currentYear)); const [type, setType] = useState("Tous"); const rows = useMemo(() => data.members.flatMap(member => (Array.from(new Set(data.activities.map(a => a.type))) as string[]).filter(t => type === "Tous" || t === type).map(t => { const ids = new Set(data.activities.filter(a => a.type === t && (period === "month" ? a.date.startsWith(month) : a.date.startsWith(year))).map(a => a.id)); const records = data.attendance.filter(x => x.memberId === member.id && ids.has(x.activityId)); const counts: any = Object.fromEntries(Object.keys(statusLabels).map(s => [s, records.filter(x => x.status === s).length])); return { member, type: t, total: records.length, ...counts, rate: records.length ? Math.round(((counts.present + counts.late) / records.length) * 100) : 0 }; })).filter(row => row.total > 0), [data, month, year, type, period]); const types = ["Tous", ...Array.from(new Set(data.activities.map(a => a.type)))] as string[];
  function backup() { const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), ...data }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `ht-gestion-sauvegarde-${today}.json`; link.click(); URL.revokeObjectURL(url); }
  return <Panel title="Statistiques de présence" action={<Button variant="outline" onClick={backup}><Download />Sauvegarder</Button>}><div className="toolbar"><NativeSelect value={period} onChange={e => setPeriod(e.target.value as any)}><NativeSelectOption value="month">Par mois</NativeSelectOption><NativeSelectOption value="year">Par année</NativeSelectOption></NativeSelect>{period === "month" ? <Input type="month" value={month} onChange={e => setMonth(e.target.value)} /> : <Input type="number" value={year} onChange={e => setYear(e.target.value)} />}<NativeSelect value={type} onChange={e => setType(e.target.value)}>{types.map(x => <NativeSelectOption key={x}>{x}</NativeSelectOption>)}</NativeSelect></div><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>Membre</TableHead><TableHead>Activité</TableHead><TableHead>Présent</TableHead><TableHead>Retard</TableHead><TableHead>Absent</TableHead><TableHead>Justifié</TableHead><TableHead>Taux</TableHead></TableRow></TableHeader><TableBody>{rows.map((r: any) => <TableRow key={`${r.member.id}-${r.type}`}><TableCell><strong>{memberName(r.member)}</strong><small>{r.member.matricule}</small></TableCell><TableCell>{r.type}</TableCell><TableCell>{r.present}</TableCell><TableCell>{r.late}</TableCell><TableCell>{r.absent}</TableCell><TableCell>{r.justified}</TableCell><TableCell><b className={r.rate >= 75 ? "status-ok" : "status-warn"}>{r.rate}%</b></TableCell></TableRow>)}</TableBody></Table></div>{!rows.length && <Empty text="Aucune présence sur la période sélectionnée." />}</Panel>;
}
